# Site
repository: weweweme/weweweme.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 0

# Personal info
name: 주진수
title: 유니티 클라이언트 프로그래머
email: argentdarae@gmail.com
# email_title: Email (Email title override)
website: https://argentdarae.tistory.com/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  weweweme
linkedin_username: jinsoo-joo




# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  1년차 유니티 클라이언트 프로그래머로서 2023년 경일 게임 아카데미 모바일 게임 개발과정을 수료하였고, 2024년 와드게임즈에서 유니티 클라이언트 프로그래머로 근무했습니다.
  
  2024년 출시한 모바일 온라인 스포츠 게임 [WILD BOWL : ZOOPORTS](https://drive.google.com/file/d/1YMdBGG-63N5Gk61V5LoQDDgErajbiyKx/view?usp=drive_link)의 클라이언트 개발을 담당하였고, 2025년 스팀 출시한 인디게임 [KEEPING NIGHT](https://drive.google.com/file/d/1XYowUJaaYr2ZNqdmIjAWHzcmgGxQ8KB9/view?usp=drive_link)에서 클라이언트 개발을 담당하였습니다.

  저에게 <b>개발은 상대방의 문제를 해결하고 서로에게 이득이 되는 결과물을 만드는 과정</b>입니다. 이를 위해 스스로에게 엄격하고 늘 최선을 다하며, 항상 열린 자세로 배우고 변화에 유연하게 대처함으로써 더 나은 결과를 추구합니다.

  <mark>재미있는 게임</mark>, <mark>완성도 높은 결과물</mark>, <mark>협업자들과의 효율적이고 원활한 소통</mark> 이라는 세 가지 핵심 가치를 추구하며, 항상 새로운 것을 배우고 도전하는 것을 즐깁니다.


content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 주식회사 와드게임즈
        sub_title: 유니티 클라이언트 프로그래머
        caption: 2023.09 - 2024.08
        link: wardgames.info
        quote: >
          누적 다운로드 1000+, 온라인 스포츠 게임 [WILD BOWL : ZOOPORTS] 출시
        description: | # this will include new lines to allow paragraphs
          - 상점, 결제 프로세스 및 광고·알림 시스템 설계 및 구현
          - MVP 패턴을 사용한 UI 시스템 리팩토링 및 UI 연출 전반을 담당
          - 튜토리얼 시스템 구현
          - 애플 앱스토어 빌드 제출 및 심사 이슈 대응

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: 경일 게임 아카데미 모바일 게임 개발과정
        caption: 2022.12 - 2023.06
        quote: >
          7개월 간의 유니티 게임 개발 교육
        description: | # this will include new lines to allow paragraphs
          - C# 언어 기초 및 유니티 엔진 사용법 학습
          - 자료구조 및 알고리즘 학습
          - 2D/3D 게임 개발 프로젝트 수행, 개발 프로세스 및 협업 경험


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag